site_name: OGC API Leermodule
site_url: https://www.acceptatie.pdok.nl/leermodule
site_description: Een leermodule met achtergrondinformatie en oefeningen om te leren werken met OGC API's van PDOK
repo_url: https://github.com/PDOK/leermodule-ogc-api/
edit_uri: edit/master/docs/
theme:
  language: nl
  name: material
  palette:
   primary: custom
   accent: light blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.footer
    - search.suggest
    - search.highlight
    - navigation.top
    - header.autohide
    - content.code.copy
  logo: assets/pdok.png
  favicon: assets/pdok.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
plugins:
  - search:
      lang: nl
nav:
    - Introductie: index.md
    - Achtergrondinformatie: 
        - Achtergondinformatie: achtergrondinformatie/Achtergrondinformatie.md
        - Terugblik: achtergrondinformatie/Terugblik.md
    - OGC API - Tiles: 
        - Introductie: tiles/Introductie.md
        - Verken OGC API - Tiles in de browser: tiles/Verken OGC API - Tiles in de browser.md
        - Maak een kaart met OGC API - Tiles: tiles/Maak een kaart met OGC API - Tiles.md
        - Terugblik: tiles/Terugblik.md
    - OGC API - Features:
        - Introductie: features/Introductie.md
        - Verken OGC API - Features in de browser: features/Verken OGC API - Features in de browser.md
        - Bevraag OGC API - Features met curl: features/Bevraag OGC API - Features met curl.md
        - Maak een interactieve kaart met OGC API - Features: features/Maak een interactieve kaart met OGC API - Features.md
        - Terugblik: features/Terugblik.md
    - Afronding: Afronding.md
    - Referenties:
        - Verwijzingen: referenties/features.md 

