site_name: OGC API Leermodule
site_url: https://www.acceptatie.pdok.nl/leermodule
site_description: Een leermodule met achtergrondinformatie en oefeningen om te leren werken met OGC API's van PDOK
repo_url: https://github.com/PDOK/leermodule-ogc-api/
edit_uri: edit/master/docs/
theme:
  language: nl
  name: material
  palette:
   primary: custom
   accent: light blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.footer
    - search.suggest
    - search.highlight
    - navigation.top
    - header.autohide
    - content.code.copy
  logo: assets/pdok.png
  favicon: assets/pdok.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search:
      lang: nl
nav:
    - Introductie: index.md
    - Achtergrondinformatie: 
        - Introductie: achtergrondinformatie/Introductie.md
        - Wat is geo-informatie?: achtergrondinformatie/Wat is geo-informatie.md
        - Wat doet het Kadaster / PDOK?: achtergrondinformatie/Wat doet het Kadaster - PDOK.md
        - Wat zijn OGC API's?: achtergrondinformatie/Wat zijn OGC APIs.md
        - Het belang van standaarden: achtergrondinformatie/Het belang van standaarden.md 
        - Terugblik: achtergrondinformatie/Terugblik.md
    - OGC API - Tiles: 
        - Introductie: tiles/Introductie.md
        - Verken OGC API - Tiles in de browser: tiles/Verken OGC API - Tiles in de browser.md
        - Analyseer een voorbeeldkaart: tiles/Analyseer een voorbeeldkaart.md
        - Casus - Maak een kaart met OGC API - Tiles: tiles/Casus - Maak een kaart met OGC API - Tiles.md
        - Terugblik: tiles/Terugblik.md
    - OGC API - Features:
        - Introductie: features/Introductie.md
        - Verken OGC API - Features in de browser: features/Verken OGC API - Features in de browser.md
        - Bevraag OGC API - Features met curl: features/Bevraag OGC API - Features met curl.md
        - Casus - Analyseer data met OGC API - Features met Python: features/Casus - Analyseer data met OGC API - Features met Python.md
        - Terugblik: features/Terugblik.md
    - Afronding: Afronding.md
    - Community: Community.md
    - Referenties:
        - Verwijzingen: referenties/features.md 

